ProjectOnPioneerWeb_publish/Models/PioneerContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;

namespace ProjectOnPioneerWeb_publish.Models
{
    
    public class PioneerContext : DbContext
    {
         public PioneerContext() 
            :base("name = DBConnectionString")
            //base(@"Data Source=USER-PC\SQL2014;Initial Catalog=PioneerDatabase;trusted_connection=true")
           // public PioneerContext() : base("name="connectionString")
       
        {

        }
       
        public DbSet<PioneerData> PioneerDatas { get; set; }
    }
}

ProjectOnPioneerWeb_publish/Models/PioneerData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ProjectOnPioneerWeb_publish.Models
{
    public class PioneerData
    {
        [Key]
        public int Id { get; set; }
        public string Interestedin { get; set; }
        [Required(ErrorMessage = "Please insert your full name")]
        public string Yourfullname { get; set; }


        [Required(ErrorMessage = "Please enter the Contact No .")]
        [StringLength(11)]
        public string ContactNo { get; set; }


        [Required(ErrorMessage = "Please enter your email address")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Emailid")]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter correct email")]
        public string Emailid { get; set; }
        [StringLength(11)]
        public string AlternativeNo { get; set; }
        public string BestTimeToCall { get; set; }
        [Required(ErrorMessage = "please input the message in the given box")]
        [StringLength(200)]
        public string YourMessage { get; set; }

        public bool isSubmitted { get; set; }
    }
}

ProjectOnPioneerWeb_publish/Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectOnPioneerWeb_publish.Models;

namespace ProjectOnPioneerWeb_publish.Controllers
{
    public class homeController : Controller
    {
        // GET: home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Careers()
        {
            return View();
        }
      
        public ActionResult AboutUs()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ContactUs()
        {
            PioneerData model = new PioneerData();
            return View(model);
           
        }
        [HttpPost]
        public ActionResult ContactUs(PioneerData model)
        {
            if (!ModelState.IsValid)
            { return View(); }
            using (PioneerContext objContext = new PioneerContext())
            {
                objContext.PioneerDatas.Add(model);
                objContext.SaveChanges();
            }
            model.isSubmitted = true;
            return View(model);


        }
       
        public ActionResult PrivacyPolicy()
        {
            return View();
        }
        public ActionResult CookiePolicy()
        {
            return View();
        }
    }
}

ProjectOnPioneerWeb_publish/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title>Pioneer-Web</title>
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">


    <!-- CSS  -->
    <link href="~/Content/css/material-design-iconic-font.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/ninja-slider.css" rel="stylesheet" type="text/css" />




    <!--owl-carousel-->
    <link href="~/Content/css/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/owl.transitions.css" rel="stylesheet" type="text/css">

    <link href="~/Content/css/style.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/validation.css" rel="stylesheet" type="text/css" />

    <!--[if lt IE 9]>
       <link href="/Content/css/ie8.css" rel="stylesheet" />
       <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <script>
            <script type="text/javascript">
              WebFontConfig = {
                google: { families: [ 'Open+Sans:400,300,600,700:latin' ] }
              };
              (function() {
                var wf = document.createElement('script');
                wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
                wf.type = 'text/javascript';
                wf.async = 'true';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(wf, s);
              })();
            </script>
        </script>
     <![endif]-->

</head>


<body>


    <header>
        <nav id="header" class="navbar navbar-fixed-top menuSection">
            <div id="header-container" class="container navbar-container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a id="brand" class="navbar-brand" href="@Url.Action("Index","home")"><img src="~/Content/img/logo.png" alt=""></a>







                </div>
                <div id="navbar" class="collapse navbar-collapse cl-effect-1 navbar-right">
                    <!--<ul class="nav navbar-nav editNav">
                         <li class="active"><a href="index.html">Home</a></li>
                         <li><a href="about_us.html">About Us</a></li>
                         <li><a href="careers.html">Careers</a></li>
                         <li><a href="#">Blog</a></li>
                         <li><a href="contact_us.html">Contact Us</a></li>
                     </ul>-->
                    <ul class="nav navbar-nav editNav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("AboutUs", "AboutUs", "Home")</li>

                        <li>@Html.ActionLink("Careers", "Careers", "Home")</li>
                        @*<li>@Html.ActionLink("Blog", "Blog", "Blog")</li>*@
                        <li>@Html.ActionLink("ContactUs", "ContactUs", "Home")</li>
                    </ul>
                </div><!-- /.nav-collapse -->









            </div><!-- /.container -->
        </nav><!-- /.navbar -->
    </header><!--End_header-->


    @RenderBody()




    <footer class="page-footer">
        <div class="container">
            <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12 padding-right">
                <h2 class="f-divtitle">LOGO</h2>
                <p>
                    We are a professional and well established online lead generation company. We sell high quality life insurance leads, health insurance leads, medical insurance leads, debt management leads, credit card leads, loan leads, mortgage leads, equity leads, business and consumer data to the leading and most respected UK companies and individuals interested in buying leads.
                    <br />
                    <a href="#">Read More...</a>
                </p>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 padding-left">
                <h2 class="f-divtitle">QUICK LINKS</h2>
                <ul class="f-Link">
                    <!--<li class="active"><a href="index.html">Home</a></li>
                    <li><a href="AboutUs/AboutUs">About Us</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="contact_us.html">Contact Us</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Cookie Policy</a></li>-->
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("AboutUs", "AboutUs", "Home")</li>
                    @*<li>@Html.ActionLink("Blog", "Blog", "Blog")</li>--> *@
                    <li>@Html.ActionLink("ContactUs", "ContactUs", "Home")</li>
                    <li>@Html.ActionLink("PrivacyPolicy", "PrivacyPolicy", "Home")</li>
                    <li>@Html.ActionLink("CookiePolicy", "CookiePolicy", "Home")</li>
                </ul>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 padding-left">
                <h2 class="f-divtitle">SUBCRIBER NOW</h2>
                <p>
                    We'll send email notifications everytime we release new iLDS implement.
                </p>
                <div class="input-group updateNews">
                    <input type="text" class="form-control" placeholder="Enter your email">
                    <span class="input-group-btn">
                        <button class="btn-theme-colored" type="button"><img src="~/Content/img/send-icon.png"></button>
                    </span>
                </div>
                <ul class="social_media">
                    <li><a href=""><i class="zmdi zmdi-facebook zmdi-hc-fw"></i></a></li>
                    <li><a href=""><i class="zmdi zmdi-twitter zmdi-hc-fw"></i></a></li>
                    <li><a href=""><i class="zmdi zmdi-google-plus zmdi-hc-fw"></i></a></li>
                    <li><a href=""><i class="zmdi zmdi-linkedin zmdi-hc-fw"></i></a></li>
                    <div class="clr"></div>
                </ul>
            </div>
            <div class="clr"></div>
            <br />
            <hr />
            <p class="copyright-Text">Copyright pioneer-web.co.uk © 2010 - 2017 — All rights reserved.</p>
        </div>
    </footer><!--End_footer-->





    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/Content/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery-ui.js"></script>
    <script type="text/javascript" src="~/Content/js/ninja-slider.js"></script>

    <script type="text/javascript" src="~/Content/js/custom.js"></script>

</body>
</html>

ProjectOnPioneerWeb_publish/Views/home/AboutUs.cshtml
<div class="wrapper-body">
    <div class="pageheader-Title">
        <h3>
            About Us
            <span>Home / <a href="#">AboutUs</a></span>
        </h3>
    </div>
    <section class="welcome-section">
        <div class="container">
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 no-padding">
                <img src="~/Content/img/aboutus_pic.png" alt="about-picture" class="img-responsive" style="width:100%;">
            </div>
            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 padding-left">
                <h2>Lead generation <span style="color:#00c5dc;">experts</span></h2>
                <p>
                    We are a professional and well established online lead generation company. We sell high quality life insurance leads, health insurance leads, medical insurance leads, debt management leads, credit card leads, loan leads, mortgage leads, equity leads, business and consumer data to the leading and most respected UK companies and individuals interested in buying leads. Pioneer web was formed by a team of individuals with diverse backgrounds in an advanced web marketing and distribution system developments. The professional experience we hold have been instrumental in many of the innovations in the market place. We are committed to providing a down to earth, friendly and ethical service and look forward to helping you and your business grow and maximize profit potential.
                </p>
            </div>
            <div class="clr"></div>
            <br />
            <p>
                <b>Our Mission</b> is to expand our business by helping our clients get good quality leads suited to their needs in the most ethical manner. We aim to generate leads with prospects that are in the market for your services, uncovering the opportunities that are of most value to your company.
                Our dedicated team are driven by a passion to deliver for our clients and aim to generate qualified new business opportunities. Understanding our customer’s needs, we offer customized quality, genuine, relevant and reliable leads.
            </p>
        </div>
    </section><!--End_welcome-section-->

    <section class="testimonial-section">
        <div class="container">
            <div class="page-title">
                <p>Testimonials</p>
                <h1>What <span>Other Say</span></h1>
                <img src="~/Content/img/titleborder.png" alt="titleborder">
            </div>
            <div class="col-md-12 no-padding" data-wow-delay="0.2s">
                <div class="carousel slide" data-ride="carousel" id="quote-carousel">
                    <!-- Carousel Slides / Quotes -->
                    <div class="carousel-inner text-center edittestmonial">
                        <!-- Quote 1 -->
                        <div class="item active">
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <div class="quote_icon">
                                        <img src="~/Content/img/quote_L.png" alt="quote_L" class="quoteicon_l">
                                        <img src="~/Content/img/quote_R.png" alt="quote_R" class="quoteicon_r">
                                    </div>
                                    <p>
                                        We focus on using the latest technologies to provide qualified leads and best possible benefit on your investment to help you <br />to achieve your sales target through our lead generation services.
                                    </p>
                                    <span>Someone famous</span>
                                </div>
                            </div>
                        </div>
                        <!-- Quote 2 -->
                        <div class="item">
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <div class="quote_icon">
                                        <img src="~/Content/img/quote_L.png" alt="quote_L" class="quoteicon_l">
                                        <img src="~/Content/img/quote_R.png" alt="quote_R" class="quoteicon_r">
                                    </div>
                                    <p>
                                        We focus on using the latest technologies to provide qualified leads and best possible benefit on your investment to help you <br />to achieve your sales target through our lead generation services.
                                    </p>
                                    <span>Someone famous</span>
                                </div>
                            </div>
                        </div>
                        <!-- Quote 3 -->
                        <div class="item">
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <div class="quote_icon">
                                        <img src="~/Content/img/quote_L.png" alt="quote_L" class="quoteicon_l">
                                        <img src="~/Content/img/quote_R.png" alt="quote_R" class="quoteicon_r">
                                    </div>
                                    <p>
                                        We focus on using the latest technologies to provide qualified leads and best possible benefit on your investment to help you <br />to achieve your sales target through our lead generation services.
                                    </p>
                                    <span>Someone famous</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Carousel Buttons Next/Prev -->
                    <a data-slide="prev" href="#quote-carousel" class="left carousel-control" style="color:#00c5dc;">
                        <i class="zmdi zmdi-chevron-left zmdi-hc-fw"></i>
                    </a>
                    <a data-slide="next" href="#quote-carousel" class="right carousel-control" style="color:#00c5dc;">
                        <i class="zmdi zmdi-chevron-right zmdi-hc-fw"></i>
                    </a>
                </div>
            </div>
        </div>
    </section><!--End_testimonial-section-->
</div>

ProjectOnPioneerWeb_publish/Views/home/Careers.cshtml
<div class="wrapper-body">
    <div class="pageheader-Title">
        <h3>
            Careers
            <span>Home / <a href="#">Careers</a></span>
        </h3>
    </div>
    <section class="welcome-section">
        <div class="container">
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 no-padding">
                <img src="~/Content/img/careers_pic.png" alt="about-picture" class="img-responsive" style="width:100%;">
            </div>
            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 padding-left">
                <h2>Build careers <span style="color:#00c5dc;">with us</span></h2>
                <p><span>We value determination and smart thinking.</span></p>
                <p>
                    Essential reading for those with a professional, active and can-do attitude to work. We are looking for people who really believe they can make a difference. People with a track record of success who are competent, enthusiastic, collaborative, smart, teachable, self motivated, committed to excellence and strong results and having a positive, can do, whatever it takes attitude are welcome. If this sound like your kind of place, read on.
                </p>
                <p>
                    Pioneer Web provides a collegial and friendly work environment. At the same time it is serious about setting high standards in integrity and business practices , building innovative products and strong relationships with clients, developing its employees, and achieving real results that are nothing short of complete success for customers and the company.
                </p>
            </div>
            <div class="clr"></div>
            <br />
            <p>
                Pioneer Web provides competitive compensation and benefits and the opportunity for personal and professional growth. If you are interested please send resume on: <span>jobs@pioneer-web.co.uk</span>
            </p>
        </div>
    </section><!--End_welcome-section-->

    <section class="testimonial-section">
        <div class="container">
            <div class="page-title">
                <p>Testimonials</p>
                <h1>What <span>Other Say</span></h1>
                <img src="~/Content/img/titleborder.png" alt="titleborder">
            </div>
            <div class="col-md-12 no-padding" data-wow-delay="0.2s">
                <div class="carousel slide" data-ride="carousel" id="quote-carousel">
                    <!-- Carousel Slides / Quotes -->
                    <div class="carousel-inner text-center edittestmonial">
                        <!-- Quote 1 -->
                        <div class="item active">
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <div class="quote_icon">
                                        <img src="~/Content/img/quote_L.png" alt="quote_L" class="quoteicon_l">
                                        <img src="~/Content/img/quote_R.png" alt="quote_R" class="quoteicon_r">
                                    </div>
                                    <p>
                                        We focus on using the latest technologies to provide qualified leads and best possible benefit on your investment to help you <br />to achieve your sales target through our lead generation services.
                                    </p>
                                    <span>Someone famous</span>
                                </div>
                            </div>
                        </div>
                        <!-- Quote 2 -->
                        <div class="item">
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <div class="quote_icon">
                                        <img src="~/Content/img/quote_L.png" alt="quote_L" class="quoteicon_l">
                                        <img src="~/Content/img/quote_R.png" alt="quote_R" class="quoteicon_r">
                                    </div>
                                    <p>
                                        We focus on using the latest technologies to provide qualified leads and best possible benefit on your investment to help you <br />to achieve your sales target through our lead generation services.
                                    </p>
                                    <span>Someone famous</span>
                                </div>
                            </div>
                        </div>
                        <!-- Quote 3 -->
                        <div class="item">
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">
                                    <div class="quote_icon">
                                        <img src="~/Content/img/quote_L.png" alt="quote_L" class="quoteicon_l">
                                        <img src="~/Content/img/quote_R.png" alt="quote_R" class="quoteicon_r">
                                    </div>
                                    <p>
                                        We focus on using the latest technologies to provide qualified leads and best possible benefit on your investment to help you <br />to achieve your sales target through our lead generation services.
                                    </p>
                                    <span>Someone famous</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Carousel Buttons Next/Prev -->
                    <a data-slide="prev" href="#quote-carousel" class="left carousel-control" style="color:#00c5dc;">
                        <i class="zmdi zmdi-chevron-left zmdi-hc-fw"></i>
                    </a>
                    <a data-slide="next" href="#quote-carousel" class="right carousel-control" style="color:#00c5dc;">
                        <i class="zmdi zmdi-chevron-right zmdi-hc-fw"></i>
                    </a>
                </div>
            </div>
        </div>
    </section><!--End_testimonial-section-->
</div>

ProjectOnPioneerWeb_publish/Views/home/CookiePolicy.cshtml
@{
    ViewBag.Title = "CookiePolicy";
}

<h2>CookiePolicy</h2>

ProjectOnPioneerWeb_publish/Views/home/PrivacyPolicy.cshtml
@{
    ViewBag.Title = "PrivacyPolicy";
}

<h2>PrivacyPolicy</h2>